table DimCustomerRFM
	lineageTag: 3df91f2d-bc79-4443-a115-f38e23288f21

	column customer_key
		dataType: int64
		formatString: 0
		lineageTag: 4eb5e3fd-b155-4571-9e11-77f0e35c7f2c
		summarizeBy: none
		sourceColumn: customer_key

		annotation SummarizationSetBy = Automatic

	column recency_days
		dataType: int64
		formatString: 0
		lineageTag: 58c22d96-b03c-42ef-aaa4-08ba4c7e6f50
		summarizeBy: sum
		sourceColumn: recency_days

		annotation SummarizationSetBy = Automatic

	column frequency
		dataType: int64
		formatString: 0
		lineageTag: 691064db-25d5-423d-88d5-94504aa4e82a
		summarizeBy: sum
		sourceColumn: frequency

		annotation SummarizationSetBy = Automatic

	column monetary
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b61d0ebb-7126-4cca-849a-6c5e5da3cd09
		summarizeBy: sum
		sourceColumn: monetary

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column r_score
		dataType: int64
		formatString: 0
		lineageTag: a255b701-32ee-4626-a197-8cd223bc2eea
		summarizeBy: sum
		sourceColumn: r_score

		annotation SummarizationSetBy = Automatic

	column f_score
		dataType: int64
		formatString: 0
		lineageTag: ad9d8222-6eec-48a5-8f5c-badea47b7f86
		summarizeBy: sum
		sourceColumn: f_score

		annotation SummarizationSetBy = Automatic

	column m_score
		dataType: int64
		formatString: 0
		lineageTag: f8ef10e4-6e3f-4d07-8932-b226166152c3
		summarizeBy: sum
		sourceColumn: m_score

		annotation SummarizationSetBy = Automatic

	column rfm_total
		dataType: int64
		formatString: 0
		lineageTag: 00d699f8-2ddc-4d0a-abb5-db3c55eecb63
		summarizeBy: sum
		sourceColumn: rfm_total

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		lineageTag: 196f0bde-8ee9-48cd-977f-6818cb8975d2
		summarizeBy: none
		sourceColumn: segment

		annotation SummarizationSetBy = Automatic

	partition DimCustomerRFM = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\amars\OneDrive\Desktop\Share\Superstore project\data\processed\DimCustomerRFM.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_key", Int64.Type}, {"recency_days", Int64.Type}, {"frequency", Int64.Type}, {"monetary", type number}, {"r_score", Int64.Type}, {"f_score", Int64.Type}, {"m_score", Int64.Type}, {"rfm_total", Int64.Type}, {"segment", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

